### ISSUE TITLE
Many "mirrored" containers unnecessary

### ISSUE THREAD

**Issue by disconn3ct** [truecharts/containers#10622]
### App Name

airsonic, apache-musicindex, audacity, authelia, authentik, authentik-ldap, authentik-proxy, autobrr, babybuddy, batnoter, bazarr, beets, blocky-frontend, boinc, booksonic-air, bookstack, budge, calibre, changedetection, chevereto, clarkson, cloud9, cloudflareddns, coder, couchpotato, darktable, davos, ddclient, deluge, digikam, dillinger, dim, domoticz, doplarr, doublecommander, duckdns, emby, embystat, emulatorjs, endlessh, etherpad, filezilla, firefox, firefox-syncserver, flaresolverr, fleet, foldingathome, fossil, freshrss, golinks, grav, grocy, guacd, habridge, haste-server, headphones, healthchecks, heimdall, homarr, homebridge, homepage, hopper-rs, htpcmanager, humhub, jackett, lazylibrarian, leaf2mqtt, libreoffice, librespeed, lidarr, limnoria, littlelink-server, mainsail, medusa, midarr-server, minetest, minisatip, money-balancer, mstream, muximux, mysql-workbench, nano-wallet, netbootxyz, ngircd, nntp2nntp, novnc, nullserv, nzbget, nzbhydra2, obsidian, openvscode-server, orbital-sync, oscam, overseerr, paperless-ng, papermerge, petio, phantombot-1, photoshow, pidgin, piwigo, pixapop, plexanisync, plextraktsync, projectsend, prowlarr, pwndrop, pyload, pylon, qbittorrent, quassel-core, quassel-web, radarr, raspberrymatic, readarr, recyclarr, remmina, requestrr, resilio-sync, rsnapshot, sabnzbd, scrutiny, shiori, shorturl, sia-daemon, sickchill, sickgear, smokeping, socials, sonarr, speedflux, speedtest-exporter, speedtest-tracker, sqlitebrowser, static, storm, synclounge, tachidesk-docker, tautulli, theme-park, timetagger, transmission, trilium-notes, tt-rss, tubesync, tvheadend, twtxt, ubooquity, umami, unifi-protect-backup, valheim-server, vorta, webgrabplus, whisparr, wireguard, wireshark, xteve, znc

### SCALE Version

Not using SCALE

### App Version

master

### Application Events

```Shell
n/a
```

### Application Logs

```Shell
# Count non-metadata changes for all ghcr.io mirrors:
$ grep -Rl '^FROM ghcr.io/' mirror/ | while read a; do echo -n "$a: " ;  grep -Ev '(^LABEL|^ARG|^FROM ghcr.io/|^$)' "$a" | wc -l ; done
mirror/plex/Dockerfile: 22
mirror/digikam/Dockerfile: 0
mirror/scrutiny/Dockerfile: 0
mirror/synclounge/Dockerfile: 0
mirror/guacd/Dockerfile: 0
mirror/firefox-syncserver/Dockerfile: 0
mirror/nullserv/Dockerfile: 0
mirror/etherpad/Dockerfile: 0
mirror/theme-park/Dockerfile: 0
mirror/wireshark/Dockerfile: 0
mirror/overseerr/Dockerfile: 0
mirror/oscam/Dockerfile: 0
mirror/sickchill/Dockerfile: 0
mirror/boinc/Dockerfile: 0
mirror/deluge/Dockerfile: 0
mirror/calibre/Dockerfile: 0
mirror/ddclient/Dockerfile: 0
mirror/pixapop/Dockerfile: 0
mirror/booksonic-air/Dockerfile: 0
mirror/bookstack/Dockerfile: 0
mirror/twtxt/Dockerfile: 0
mirror/ngircd/Dockerfile: 0
mirror/batnoter/Dockerfile: 0
mirror/airsonic/Dockerfile: 0
mirror/tachidesk-docker/Dockerfile: 0
mirror/phantombot-1/Dockerfile: 0
mirror/smokeping/Dockerfile: 0
mirror/umami/Dockerfile: 0
mirror/nzbget/Dockerfile: 0
mirror/littlelink-server/Dockerfile: 0
mirror/photoshow/Dockerfile: 0
mirror/changedetection/Dockerfile: 0
mirror/golinks/Dockerfile: 0
mirror/babybuddy/Dockerfile: 0
mirror/money-balancer/Dockerfile: 0
mirror/habridge/Dockerfile: 0
mirror/pylon/Dockerfile: 0
mirror/jackett/Dockerfile: 0
mirror/darktable/Dockerfile: 0
mirror/htpcmanager/Dockerfile: 0
mirror/budge/Dockerfile: 0
mirror/tautulli/Dockerfile: 0
mirror/pyload/Dockerfile: 0
mirror/couchpotato/Dockerfile: 0
mirror/humhub/Dockerfile: 0
mirror/firefox/Dockerfile: 0
mirror/lidarr/Dockerfile: 0
mirror/domoticz/Dockerfile: 0
mirror/resilio-sync/Dockerfile: 0
mirror/hopper-rs/Dockerfile: 0
mirror/speedtest-tracker/Dockerfile: 0
mirror/apache-musicindex/Dockerfile: 0
mirror/sia-daemon/Dockerfile: 0
mirror/endlessh/Dockerfile: 0
mirror/doublecommander/Dockerfile: 0
mirror/readarr/Dockerfile: 0
mirror/filezilla/Dockerfile: 0
mirror/homepage/Dockerfile: 0
mirror/shorturl/Dockerfile: 0
mirror/ubooquity/Dockerfile: 0
mirror/medusa/Dockerfile: 0
mirror/valheim-server/Dockerfile: 0
mirror/qbittorrent/Dockerfile: 0
mirror/coder/Dockerfile: 0
mirror/speedflux/Dockerfile: 0
mirror/petio/Dockerfile: 0
mirror/nano-wallet/Dockerfile: 0
mirror/remmina/Dockerfile: 0
mirror/vorta/Dockerfile: 0
mirror/unifi-protect-backup/Dockerfile: 0
mirror/whisparr/Dockerfile: 0
mirror/piwigo/Dockerfile: 0
mirror/healthchecks/Dockerfile: 0
mirror/sonarr/Dockerfile: 0
mirror/sqlitebrowser/Dockerfile: 0
mirror/netbootxyz/Dockerfile: 0
mirror/mysql-workbench/Dockerfile: 0
mirror/recyclarr/Dockerfile: 0
mirror/foldingathome/Dockerfile: 0
mirror/embystat/Dockerfile: 0
mirror/leaf2mqtt/Dockerfile: 0
mirror/authentik-proxy/Dockerfile: 0
mirror/pwndrop/Dockerfile: 0
mirror/quassel-web/Dockerfile: 0
mirror/nzbhydra2/Dockerfile: 0
mirror/orbital-sync/Dockerfile: 0
mirror/lazylibrarian/Dockerfile: 0
mirror/sickgear/Dockerfile: 0
mirror/projectsend/Dockerfile: 0
mirror/tt-rss/Dockerfile: 0
mirror/requestrr/Dockerfile: 0
mirror/dim/Dockerfile: 0
mirror/plexanisync/Dockerfile: 0
mirror/shiori/Dockerfile: 0
mirror/headphones/Dockerfile: 0
mirror/clarkson/Dockerfile: 0
mirror/wireguard/Dockerfile: 0
mirror/blocky-frontend/Dockerfile: 0
mirror/rsnapshot/Dockerfile: 0
mirror/speedtest-exporter/Dockerfile: 0
mirror/librespeed/Dockerfile: 0
mirror/pidgin/Dockerfile: 0
mirror/homebridge/Dockerfile: 0
mirror/transmission/Dockerfile: 0
mirror/audacity/Dockerfile: 0
mirror/nntp2nntp/Dockerfile: 0
mirror/midarr-server/Dockerfile: 0
mirror/bazarr/Dockerfile: 0
mirror/authentik-ldap/Dockerfile: 0
mirror/fleet/Dockerfile: 0
mirror/znc/Dockerfile: 0
mirror/quassel-core/Dockerfile: 0
mirror/raspberrymatic/Dockerfile: 0
mirror/authentik/Dockerfile: 0
mirror/duckdns/Dockerfile: 0
mirror/cloud9/Dockerfile: 0
mirror/autobrr/Dockerfile: 0
mirror/davos/Dockerfile: 0
mirror/mstream/Dockerfile: 0
mirror/grocy/Dockerfile: 0
mirror/radarr/Dockerfile: 0
mirror/papermerge/Dockerfile: 0
mirror/socials/Dockerfile: 0
mirror/openvscode-server/Dockerfile: 0
mirror/flaresolverr/Dockerfile: 0
mirror/homarr/Dockerfile: 0
mirror/dillinger/Dockerfile: 0
mirror/mainsail/Dockerfile: 0
mirror/fossil/Dockerfile: 0
mirror/authelia/Dockerfile: 0
mirror/static/Dockerfile: 0
mirror/paperless-ng/Dockerfile: 0
mirror/libreoffice/Dockerfile: 0
mirror/haste-server/Dockerfile: 0
mirror/chevereto/Dockerfile: 0
mirror/limnoria/Dockerfile: 0
mirror/timetagger/Dockerfile: 0
mirror/trilium-notes/Dockerfile: 0
mirror/prowlarr/Dockerfile: 0
mirror/grav/Dockerfile: 0
mirror/minetest/Dockerfile: 0
mirror/storm/Dockerfile: 0
mirror/beets/Dockerfile: 0
mirror/doplarr/Dockerfile: 0
mirror/muximux/Dockerfile: 0
mirror/emulatorjs/Dockerfile: 0
mirror/minisatip/Dockerfile: 0
mirror/xteve/Dockerfile: 0
mirror/emby/Dockerfile: 0
mirror/heimdall/Dockerfile: 0
mirror/webgrabplus/Dockerfile: 0
mirror/obsidian/Dockerfile: 0
mirror/tvheadend/Dockerfile: 0
mirror/plextraktsync/Dockerfile: 0
mirror/tubesync/Dockerfile: 0
mirror/novnc/Dockerfile: 0
mirror/freshrss/Dockerfile: 0
mirror/cloudflareddns/Dockerfile: 0
mirror/sabnzbd/Dockerfile: 0
```

### Application Configuration

n/a

### Describe the bug

https://github.com/truecharts/containers#purpose :
> This is to get around Docker Hub rate-limiting (100 pulls / 6 hours, or authenticated 200 pulls / 6 hours). It is considered a stop-gap until the maintainers of the applications below support a different Container Registry.

Looking at the actual Dockerfiles, it appears that there are about 160 containers mirrored here from elsewhere on GH with no changes.

I listed them in app logs but I am happy to open bugs for each individual application if that is preferred. (Of the GitHub-sourced mirrors, only plex appears to be modified.)

### To Reproduce

1. Clone repo
2. ```$ grep -Rl '^FROM ghcr.io/' mirror/ | while read a; do echo -n "$a: " ;  grep -Ev '(^LABEL|^ARG|^FROM ghcr.io/|^$)' "$a" | wc -l ; done```

### Expected Behavior

> It is considered a stop-gap until the maintainers of the applications below support a different Container Registry.

Expected behavior: None of the 159 unchanged containers are "mirrored"

> We also sometimes need to apply small patches and additions for our users: For example, adding nano and extra-packages to Nextcloud

Expected behavior: Only `plex` is both sourced from github and modified. The unchanged containers are used from their trusted upstream Github sources.

### Screenshots

n/a

### Additional Context

n/a

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.

**Comment by Ornias1993** [comment]
The readme on this repository is wrong.
It was a shameless copy-paste from back in the day and does not represent the reasons why we mirror. 

I'll update it.

**Comment by Ornias1993** [comment]
Readme updated.
Issue closed because the reason of filing is based on a wrong assumption caused by the bad readme.
