### ISSUE TITLE
image for transmission

### ISSUE THREAD

**Issue by xstar97** [truecharts/containers#15273]
### Is your feature request related to a problem?

oneDr0p dep transmission

### Describe the solution you'd like

build our own image

### Describe alternatives you've considered

switch to a different app

### Additional context

ghcr.io/onedr0p/transmission

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

**Comment by stavros-k** [comment]
btw, onedr0p re-added transmission v4

**Comment by xstar97** [comment]
I am all for it.

**Comment by urza** [comment]
Current stable chart for Transmission is using v3. Can we update to v4 which is major Transmission rewrite and modernization?

**Comment by stavros-k** [comment]
PRs are welcome
