### ISSUE TITLE
Update resilio-sync mirror

### ISSUE THREAD

**Issue by TzeWey** [truecharts/containers#15781]
### Is your feature request related to a problem?

An updated version of Resilio Sync is available (v2.7.3.1381)
The current mirrored version is v2.7.2.1375 ([link](https://github.com/truecharts/containers/blob/master/mirror/resilio-sync/Dockerfile#L1))

### Describe the solution you'd like

Update the mirror with the latest version available from https://hub.docker.com/r/resilio/sync
It is an official upstream container; Unsure if it will work with TrueCharts out of the box, but it seems like it should.

### Describe alternatives you've considered

Creating a Chart in a private Catalog (have done it before and it is not easy to maintain)

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

**Comment by stavros-k** [comment]
Current mirror is from LSIO. 
It is definatelly going to need changes to use the upstream container.
If upstream container is better (eg runs as a non-privileged user or ahs other benefits of using).
Feel free to open an issue in the charts repo.
