### ISSUE TITLE
Duplicacy - Container listed, but not built

### ISSUE THREAD

**Issue by kutyla-philipp** [truecharts/containers#4530]
### App Name

duplicacy

### SCALE Version

22.02.1

### App Version

latest_0.0.11

### Application Events

```Shell
Back-off pulling image "tccr.io/truecharts/duplicacy:latest"
```

### Application Logs

```Shell
-
```

### Application Configuration

-

### Describe the bug

It seems like the Dockerfile has not been built yet.
The image is also not listed here: https://github.com/orgs/truecharts/packages?ecosystem=container&visibility=public

### To Reproduce

1. Pull the image

### Expected Behavior

I can pull the image.

### Screenshots

-

### Additional Context

-

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.

**Comment by Ornias1993** [comment]
See announcements.

**Comment by Ornias1993** [comment]
Also: incubator means “not fully finished”
