### ISSUE TITLE
multi-init: exec format error on arm64

### ISSUE THREAD

**Issue by samip5** [truecharts/containers#8361]
### App Name

multi-init

### SCALE Version

Not using SCALE

### App Version

N/A

### Application Events

```Shell
Type     Reason                  Age                    From                     Message
  ----     ------                  ----                   ----                     -------
  Warning  FailedScheduling        5m49s                  default-scheduler        0/5 nodes are available: 5 pod has unbound immediate PersistentVolumeClaims. preemption: 0/5 nodes are available: 5 Preemption is not helpful for scheduling.
  Warning  FailedScheduling        5m48s                  default-scheduler        0/5 nodes are available: 5 pod has unbound immediate PersistentVolumeClaims. preemption: 0/5 nodes are available: 5 Preemption is not helpful for scheduling.
  Normal   Scheduled               5m46s                  default-scheduler        Successfully assigned databases/pgadmin-7896dcfff5-mgjgz to k8s-worker5
  Normal   SuccessfulAttachVolume  5m35s                  attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-c77b09b8-f177-4a98-88ea-8932dff24fd2"
  Normal   Pulled                  5m27s                  kubelet                  Container image "quay.io/k8tz/k8tz:0.8.0@sha256:7bba4420c8decfad816cc77a180f121cfc1e0e51058dec7662837b4ba41812b7" already present on machine
  Normal   Created                 5m26s                  kubelet                  Created container provide-timezone
  Normal   Started                 5m26s                  kubelet                  Started container provide-timezone
  Normal   Pulling                 5m25s                  kubelet                  Pulling image "tccr.io/truecharts/multi-init:v0.0.1@sha256:5c1367f74527c7cdf02d034d721d0d7ac15ac08f5ab0b7f9106152c05e053618"
  Normal   Pulled                  4m17s                  kubelet                  Successfully pulled image "tccr.io/truecharts/multi-init:v0.0.1@sha256:5c1367f74527c7cdf02d034d721d0d7ac15ac08f5ab0b7f9106152c05e053618" in 1m7.933463063s
  Normal   Pulled                  2m36s (x4 over 4m)     kubelet                  Container image "tccr.io/truecharts/multi-init:v0.0.1@sha256:5c1367f74527c7cdf02d034d721d0d7ac15ac08f5ab0b7f9106152c05e053618" already present on machine
  Normal   Created                 2m36s (x5 over 4m12s)  kubelet                  Created container prepare
  Normal   Started                 2m36s (x5 over 4m12s)  kubelet                  Started container prepare
  Warning  BackOff                 20s (x17 over 3m59s)   kubelet                  Back-off restarting failed container
```

### Application Logs

```Shell
k logs -n databases pgadmin-7896dcfff5-mgjgz prepare
exec /bin/sh: exec format error
```

### Application Configuration

N/A

### Describe the bug

The container is only built for amd64 which should be fixed to also build on arm64.

### To Reproduce

1. Create an arm64 k8s cluster
2. Try to deploy any that uses the initcontainer
3. Notice it failing.

### Expected Behavior

It would just work.

### Screenshots

N/A

### Additional Context

N/A

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.

**Comment by Ornias1993** [comment]
We do not support arm64 and also don't build images for it.

**Comment by samip5** [comment]
Hi,

That means that M1 macs are also unsupported which is a shame.

**Comment by Ornias1993** [comment]
Our primary target audience is currently running TrueNAS SCALE, which also does not support ARM64.

Besides that we are actively working to support Native Helm on what is basically the same hardware platform (but instead running helm directly). We never intended to also increase hardware platform support by supporting Native Helm.

But, most importantly, neither to a lot of the containers used.
So we would need to seperately start documenting which Charts do and do not support ARM64, add dedicated testing **AND** both contributors and maintainers to do so (because I definately have no interest in maintaining it, because I simply are short on time already)

**Comment by gclawes** [comment]
With the move to Talos, can this be reconsidered?  Raspberry Pi is a popular hardware target for Talos Linux

**Comment by Ornias1993** [comment]
Please dont necro issues.
The package this issue is about doesn't even exist anymore afaik
